### ISSUE TITLE
Icons are gone with 2021.11

### ISSUE THREAD

**Issue by chbndrhnns** [marrobHD/firetv-card#10]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
2021.11

**Last working release (if known):**
2021.10

**Browser and Operating System:**

iOS app of Homeassistant 

**Description of problem:**

All icons of my Lovelace card are gone.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by wuschel1337** [comment]
I have the same, all icons are gone under 2021.11.

**Comment by kksligh** [comment]
Same issue

**Comment by datbilling** [comment]
Same issue here

**Comment by Madseason41** [comment]
Same here

**Comment by ogizhelev** [comment]
![Capture](https://user-images.githubusercontent.com/20031065/143051220-65e30aa0-4fc0-4c75-b308-c0b3fa21e144.PNG)
same

**Comment by sinclairfr** [comment]
same here... ffs

**Comment by Madseason41** [comment]
Is this repo still active? May be time to look for a replacement.

**Comment by kksligh** [comment]
Seems so...any ideas?

**Comment by Madseason41** [comment]
I think the roku card is similar and it had issues as well. I tried to look at it figure out what changes were needed but I guess I'm not that smart lol.

**Comment by ogizhelev** [comment]
I have migrated to Roku card - works perfectly fine , as not sure when this one will be fixed

**Comment by chbndrhnns** [comment]
> I have migrated to Roku card

Does it work fine with the Fire TV stick, as well? If yes, what did you do to migrate?

**Comment by marrobHD** [comment]
I've merged the PR. Please clear the cache of the HA companion app and on the ha webui press F5 to clear cache.

**Comment by chbndrhnns** [comment]
Many thanks!
