### ISSUE TITLE
tv: false not hiding power buttons

### ISSUE THREAD

**Issue by wojtek14a** [marrobHD/firetv-card#3]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v0.1.1

**Last working release (if known):**
unknown
**Browser and Operating System:**

- Google Chrome, 81.0.4044.138 (Official) (64-bit)

- Windows 10 10.0.18363

**Description of problem:**

In the README section you specify that after setting `tv` parameter to `false` both volume and **power** buttons will be hidden. From my observations I can tell that only volume buttons are hidden, power ones remain as there were with `tv` set to `true`.

![image](https://user-images.githubusercontent.com/10120476/81237772-b50ab900-9000-11ea-94c7-6011221f594a.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
I would like to hide power buttons as well, either with `tv: false` or another dedicated config variable.

**Comment by marrobHD** [comment]
Thanks wojtek14a for the bug report. Pushed a fix. Update and don´t forget to clear the cache.

**Comment by wojtek14a** [comment]
It's all good now, thank you very much!
