### ISSUE TITLE
All icons missing

### ISSUE THREAD

**Issue by wojtek14a** [marrobHD/firetv-card#4]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 0.110.0

**Last working release (if known):** 0.109.6

**Browser and Operating System:** Windows 10, Chrome 81

**Description of problem:**

After upgrading to latest version all icons are missing (both in editor and lovelace card). Probably has to do with a new way of dealing with icons described in the [release notes](https://www.home-assistant.io/blog/2020/05/20/release-110/).

![image](https://user-images.githubusercontent.com/10120476/82502384-4563f600-9af7-11ea-852c-f441066560c3.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by gregoryduckworth** [comment]
Yeah, I'm getting the same issue as well.

**Comment by monkeydriven** [comment]
Same
